name: "setup-terraform"
description: "setup terraform"
inputs:
  terraform_version:
    required: false
    description: 'versao do terraform'
    default: '1.3.3'
  terraform_wrapper:
    required: false
    description: 'terraform wrapper'
    default: false    
  terraform_path:
    type: string
    required: true
    description: 'path terraform'
  aws_role_arn:
    type: string
    required: true
    description: 'aws role arn'    
#  aws_access_key_id:
#    type: string
#    required: false
#    description: 'aws key id'
#  aws_secret_access_key:
#    type: string
#    required: false
#    description: 'aws secret'
#  aws_region:
#    type: string
#    required: false
#    description: 'aws region'    
   
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: "Configure AWS Credentials"
    uses: aws-actions/configure-aws-credentials@v1
    with:
#      aws-access-key-id: "${{ inputs.aws_access_key_id }}"
#      aws-secret-access-key: "${{ inputs.aws_secret_access_key }}"
#      aws-region: "${{ inputs.aws_region }}"
      role-to-assume: "${{ inputs.aws_role_arn }}"
      role-session-name: terraformGithubActions
      aws-region: 'us-east-2'
  - name: HashiCorp - Setup Terraform
    uses: hashicorp/setup-terraform@v2.0.2
    with:
      terraform_version: ${{ inputs.terraform_version }}
      terraform_wrapper: ${{ inputs.terraform_wrapper }}
  - name: Terraform init
    id: init
    run: |
           terraform init
    working-directory: ${{ inputs.terraform_path }}
    shell: bash
  - name: Terraform validate
    id: validate
    run: |
           terraform validate -no-color
    working-directory: ${{ inputs.terraform_path }}
    shell: bash
