name: "setup infracost"
description: "setup infracost"
inputs:
  repo_terraform_gh_token:
    type: string
    required: true
    description: 'token terraform modules'    
  repo_terraform_gh_user:    
    type: string
    required: true
    description: 'token terraform modules'
  infracost_api_key:    
    type: string
    required: true
    description: 'token infracost api'
  terragrunt_path:
    type: string
    required: true
    description: 'path terragrunt'
  token_github:
    type: string
    required: true
    description: 'token do github'
    
    
runs:
  using: "composite"
  steps:
  - name: Setup Infracost
    uses: infracost/actions/setup@v2
    with:
      api-key: ${{ inputs.INFRACOST_API_KEY }}

  - name: Checkout base branch
    uses: actions/checkout@v3
    with:
      ref: '${{ github.event.pull_request.base.ref }}'
          
  - name: setup git url.insteadof
    run: |
           git config --local --remove-section http."https://github.com/"
           git config --global url."https://${GH_USER}:${GH_TOKEN}@github.com/doliveiraorg".insteadOf "https://github.com/doliveiraorg" 
           
    shell: bash 
    env:
      GH_TOKEN: ${{ inputs.repo_terraform_gh_token }}
      GH_USER: ${{ inputs.repo_terraform_gh_user }}

  - name: Generate Infracost cost estimate baseline
    run: |
           infracost breakdown --path=${TF_ROOT} \
                                    --format=json \
                           --out-file=/tmp/infracost-base.json
    shell: bash
    env:
      TF_ROOT: ${{ inputs.terragrunt_path }}
  - name: Checkout PR branch
    uses: actions/checkout@v3
        
  - name: Generate Infracost diff
    run: |
           infracost diff --path=${TF_ROOT} \
                               --format=json \
                               --compare-to=/tmp/infracost-base.json \
                               --out-file=/tmp/infracost.json
    shell: bash
    env:
      TF_ROOT: ${{ inputs.terragrunt_path }}
  - name: Post Infracost comment
    run: |
            infracost comment github --path=/tmp/infracost.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{inputs.token_github}} \
                                     --pull-request=${{github.event.pull_request.number}} \
                                     --behavior=update
                                   
    shell: bash
