name: "setup-helmfile"
description: "setup helmfile"
inputs:
  helm_version:
    required: false
    description: 'versao do helm'
    default: '3.7.0'
  helmfile_version:
    required: false
    description: 'versao do helmfile'
    default: '0.144.0'  
runs:
  using: "composite"
  steps:
  - name: Helm tool installer
    uses: Azure/setup-helm@v3.3
    with:
      version: ${{ inputs.helm_version }}
  -  name: Install helmfile
     run: |
          curl -L -O https://github.com/roboll/helmfile/releases/download/v${{ inputs.helmfile_version }}/helmfile_linux_arm64
          mv helmfile_linux_arm64 helmfile && chmod 777 helmfile && sudo mv helmfile /usr/local/bin
          helmfile --version
     shell: bash
  - name: Install helmfile diff
    run: |
          helm plugin install https://github.com/databus23/helm-diff
          helm plugin list | grep diff && echo "plugin diff instalado com sucesso" || echo "plugin diff nao foi instalado" && exit 1       
    shell: bash
