name: "setup-terraform"
description: "setup terraform"
inputs:
  terraform_version:
    required: false
    description: 'versao do terraform'
    default: '1.3.3 '
  aws_access_key_id:
    required: true
    description: 'aws key id'
  aws_secret_access_key:
    required: true
    description: 'aws secret'
  aws_region:
    required: true
    description: 'aws region'
    
runs:
  using: "composite"
  steps:
  - name: "Configure AWS Credentials" Action For GitHub Actions
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ inputs.aws_access_key_id }}
      aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
      aws-region: ${{ inputs.aws_region }}
  - name: HashiCorp - Setup Terraform
    uses: hashicorp/setup-terraform@v2.0.2
    with:
      terraform_version: ${{ inputs.terraform_version }}
