name: "setup-terraform"
description: "setup terraform"
inputs:
  terraform_version:
    required: false
    description: 'versao do terraform'
    default: '1.3.3 '
  aws_access_key_id:
    required: false
    description: 'aws key id'
    default: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  aws_secret_access_key:
    required: false
    description: 'aws secret'
    default: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  aws_region:
    required: false
    description: 'aws region'
    default: "${{ secrets.AWS_REGION }}"

runs:
  using: "composite"
  steps:
  - name: "Configure AWS Credentials"
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: "${{ inputs.aws_access_key_id }}"
      aws-secret-access-key: "${{ inputs.aws_secret_access_key }}"
      aws-region: "${{ inputs.aws_region }}"
  - name: HashiCorp - Setup Terraform
    uses: hashicorp/setup-terraform@v2.0.2
    with:
      terraform_version: ${{ inputs.terraform_version }}
