name: "setup-terraform"
description: "setup terraform"
inputs:
  terraform_version:
    required: false
    description: 'versao do terraform'
    default: '1.3.3'
  terragrunt_version:
    required: false
    description: 'versao do terragrunt'
    default: '0.39.2'

runs:
  using: "composite"
  steps:
  - name: HashiCorp - Setup Terraform
    uses: hashicorp/setup-terraform@v2.0.2
    with:
      terraform_version: ${{ inputs.terraform_version }}
  - name: Setup Terragrunt
    uses: autero1/action-terragrunt@v1.1.0
    with:
      terragrunt_version: ${{ terragrunt_version }}
