name: "setup-terraform"
description: "setup terraform"
inputs:
  terraform_version:
    required: false
    description: 'versao do terraform'
    default: '1.3.3 '
  aws_access_key_id:
    required: false
    description: 'aws key id'
  aws_secret_access_key:
    required: false
    description: 'aws secret'
  aws_region:
    required: false
    description: 'aws region'
    
runs:
  using: "composite"
  steps:
  - name: "Configure AWS Credentials"
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      aws-region: "${{ secrets.AWS_REGION }}"
  - name: HashiCorp - Setup Terraform
    uses: hashicorp/setup-terraform@v2.0.2
    with:
      terraform_version: ${{ inputs.terraform_version }}
