
name: 'Setup polaris'
description: 'Setup polaris'
outputs:
  polaris-config:
    description: "Random number"
    value: ${{ steps.polaris-custom-check.outputs.polaris-config }}
runs:
  using: "composite"
  steps:
    - id: polaris-custom-check
      run: |
             POLARIS_CUSTOM_CHECKS=$(mktemp)
             cat templates/hello.yaml | tee $POLARIS_CUSTOM_CHECKS              
              echo "polaris-config=$(echo $POLARIS_CUSTOM_CHECKS)" >> $GITHUB_OUTPUT
      shell: bash
