
name: 'Hello World'
description: 'Greet someone'
outputs:
  polaris-config:
    description: "Random number"
    value: ${{ steps.polaris-custom-check.outputs.polaris-config }}
runs:
  using: "composite"
  steps:
    - id: polaris-custom-check
      run: |
              echo "polaris-config=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
