
name: 'Setup polaris'
description: 'Setup polaris'
outputs:
  custom-checks-file:
    description: "Random number"
    value: ${{ steps.custom-checks.outputs.custom-checks-file }}
runs:
  using: "composite"
  steps:
    - name: Polaris
      id: custom-checks
      run: |
             CUSTOM_CHECKS_FILE=$(mktemp)
             cat templates/hello.yaml | tee $CUSTOM_CHECKS_FILE              
             echo "custom-checks-file=$(echo $CUSTOM_CHECKS_FILE)" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ github.action_path }}
      
