name: "setup-teste"
description: "setup teste"
inputs:
  terraform_version:
    required: false
    description: 'versao do terraform'
    default: '1.3.3'
   
runs:
  using: "composite"
  steps:
#  - name: setup git url.insteadof
#    run: |
#            cat "${{ github.action_path }}/templates/hello.yaml"
#            cp ${{ github.action_path }}/templates/hello.yaml ${GITHUB_WORKSPACE}/
  - id: polaris
    name: teste2
    run: |
            POLARIS_CUSTOM_CHECKS=$(mktemp)
            cat templates/hello.yaml | tee $POLARIS_CUSTOM_CHECKS
            echo "wait...."
            cat $POLARIS_CUSTOM_CHECKS
            echo "plaris_config=$(echo "hello")" >> $GITHUB_OUTPUT
    shell: bash
    working-directory: ${{ github.action_path }}
  - name: teste3
    run: |
            cat ${{ steps.polaris.outputs.plaris_config }}
    shell: bash
           
