name: "setup conftest"
description: "setup conftest"
inputs:
  conftest_version:
    type: string
    required: false
    default: "0.39.2"
    description: 'conftest version'    
  bot_github_token:
    type: string
    required: true
    description: 'bot github token'        
    
runs:
  using: "composite"
  steps:
  - name: Setup conftest
    run: |
          wget "https://github.com/open-policy-agent/conftest/releases/download/v${{ inputs.conftest_version }}/conftest_${{ inputs.conftest_version }}_Linux_arm64.tar.gz"
          tar xzf conftest_${{ inputs.conftest_version }}_Linux_arm64.tar.gz
          sudo mv conftest /usr/local/bin
    shell: bash
  - name: Checkout guardrails repo
    uses: actions/checkout@v3
    with:
      persist-credentials: false
      repository: doliveiraorg/guardrails
      path: policies
      token: ${{ inputs.bot_github_token }}
