name: "setup-terraform"
description: "setup terraform"
inputs:
  terraform_version:
    required: false
    description: 'versao do terraform'
    default: '1.3.3'
  terragrunt_version:
    required: false
    description: 'versao do terragrunt'
    default: '0.39.2'
  terragrunt_path:
    type: string
    required: true
    description: 'path terragrunt'

runs:
  using: "composite"
  steps:
  - name: HashiCorp - Setup Terraform
    uses: hashicorp/setup-terraform@v2.0.2
    with:
      terraform_version: ${{ inputs.terraform_version }}
  - name: Setup Terragrunt
    uses: autero1/action-terragrunt@v1.1.0
    with:
      terragrunt_version: ${{ inputs.terragrunt_version }}

  - name: terragrunt init
    id: init
    run: |
           terragrunt init
    working-directory: ${{ inputs.terragrunt_path }}
    shell: bash
  - name: terragrunt validate
    id: validate
    run: |
           terragrunt validate
    working-directory: ${{ inputs.terragrunt_path }} 
    shell: bash
  - name: terragrunt plan
    id: plan
    run: |
           
           TERRAGRUNT_APPLY=false

           terragrunt plan -out=$PWD/plan
           
           terragrunt show -no-color plan  | grep "Plan: 2 to add, 0 to change, 0 to destroy." || TERRAGRUNT_APPLY=true
           
           echo $TERRAGRUNT_APPLY
           
    working-directory: ${{ inputs.terragrunt_path }}
    shell: bash
