name: "setup-terraform"
description: "setup terraform"
inputs:
  terraform_version:
    required: false
    description: 'versao do terraform'
    default: '1.3.3'
  terragrunt_version:
    required: false
    description: 'versao do terragrunt'
    default: '0.39.2'
  terragrunt_path:
    type: string
    required: true
    description: 'path terragrunt'
  aws_access_key_id:
    type: string
    required: false
    description: 'aws key id'
  aws_secret_access_key:
    type: string
    required: false
    description: 'aws secret'
  aws_region:
    type: string
    required: false
    description: 'aws region'    
  repo_terraform_gh_token:
    type: string
    required: true
    description: 'token terraform modules'    
  repo_terraform_gh_user:    
    type: string
    required: true
    description: 'token terraform modules'    
   
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - name: "Configure AWS Credentials"
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: "${{ inputs.aws_access_key_id }}"
      aws-secret-access-key: "${{ inputs.aws_secret_access_key }}"
      aws-region: "${{ inputs.aws_region }}"
  - name: setup git url.insteadof
    run: |
           git config --local --remove-section http."https://github.com/"
           git config --global url."https://${GH_USER}:${GH_TOKEN}@github.com/doliveiraorg".insteadOf "https://github.com/doliveiraorg"
    env:
      GH_TOKEN: ${{ inputs.repo_terraform_gh_token }}
      GH_USER: ${{ inputs.repo_terraform_gh_user }}
  
  - name: HashiCorp - Setup Terraform
    uses: hashicorp/setup-terraform@v2.0.2
    with:
      terraform_version: ${{ inputs.terraform_version }}
  - name: Setup Terragrunt
    uses: autero1/action-terragrunt@v1.1.0
    with:
      terragrunt_version: ${{ inputs.terragrunt_version }}
  - name: Terragrunt init
    id: init
    run: terragrunt init
    working-directory: ${{ inputs.terragrunt_path }}
    shell: bash
  - name: Terragrunt validate
    id: validate
    run: terragrunt validate -no-color
    working-directory: ${{ inputs.terragrunt_path }}
    shell: bash
