name: Argocd

on:
  workflow_call:
  
jobs:
  argocd:
    runs-on: ["self-hosted","Linux","ARM64","runner-devops"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         fetch-depth: 0   
    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        kubeconfig: '${{ secrets.K8S_KUBECONFIG }}'
    - name: install kubectl
      run: |
             sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
             sudo chmod +x kubectl
             sudo mkdir -p ~/.local/bin
             sudo mv ./kubectl ~/.local/bin/kubectl 
    - name: Get changed files#
      id: changed-files
      uses: tj-actions/changed-files@v36
    - name: Deploy
      id: deploy
      run: |
          ARGOCD_TEMPLATES=("app.yaml" "app.yml" "project.yaml" "project.yml")
          for file_path in ${{ steps.changed-files.outputs.all_changed_files }}
          do          
              if [ -e $file_path ];
              then
                OIFS="$IFS"
                IFS='/'
                read -a FILE_AS_LIST <<< "$file_path"
                IFS="$OIFS"
                FILE="${FILE_AS_LIST[${#FILE_AS_LIST[@]}-1]}"
                if echo "${ARGOCD_TEMPLATES[@]}" | grep -wq "$FILE";
                then
                    kubectl apply -f $file_path
                fi
              fi
            done
