name: Argocd Frankenstein

on:
  workflow_call:
  
jobs:
  argocd:
    runs-on: ["self-hosted","Linux","ARM64","runner-devops"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         fetch-depth: 0
