name: Argocd Frankenstein

on:
  workflow_call:
    inputs:
      dispatches_repo:
        type: string
        description: 'terraform repo'
        default: 'https://api.github.com/repos/doliveiraorg/terraform/dispatches'
        required: false
      dispatches_event_type:
        type: string
        description: 'dispatches event type'
        required: true           
      packer_directory:
        type: string
        description: 'packer directory'
        required: true
      packer_version:
        type: string
        description: 'packer version'
        default: '1.8.5'
        required: false
      packer_var_file:
        type: string
        description: 'packer var file'
        required: true  
  
jobs:
  argocd:
    runs-on: ["self-hosted","Linux","ARM64","runner-devops"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         fetch-depth: 0
    - name: Setup yq
      run: |
             curl -LO https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_arm64
             chmod +x yq_linux_arm64
             mv yq_linux_arm64 yq
             sudo mv yq /usr/local/bin/
    - name: debug
      run: |
             tag="gobank:20130901x"
             export IMAGE_TAG=$tag
             ls -1
             yq eval -i '.frankenstein.imageTag = env(IMAGE_TAG)' charts/values.yaml
             cat charts/values.yaml
