name: CI

on:
  workflow_call:
    inputs:
      registry:
        type: string
        description: 'Nome do container registry'
        required: false
        default: 'ghcr.io'
      username:
        type: string
        description: 'Username do container registry'
        required: false
        default: ${{ github.actor }}
      repository:
        type: string
        description: 'Repositorio'
        required: false
        default: ${{ github.repository }}
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ github.token }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker build and push
      run: |
          DATE=$(date +'%Y%m%d')
          IMAGE_ID="${DATE}${GITHUB_RUN_NUMBER}"
          docker buildx build --platform=linux/arm64,linux/amd64,linux/386 -t ${{ inputs.registry }}/${{ inputs.repository }}:$IMAGE_ID -t ${{ inputs.registry }}/${{ inputs.repository }}:latest --push . -f Dockerfile
