name: CI

on:
  workflow_call:
    inputs:
      var_1: 
        type: string
        required: true
      var_2:
        type: string
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker build and push
      env:
        ORG_NAME: "doliveiraorg"
        REPO_NAME: "golang-api-hello"
      run: |
          DATE=$(date +'%Y%m%d')
          IMAGE_ID="${DATE}${GITHUB_RUN_NUMBER}"
          docker buildx build --platform=linux/arm64,linux/amd64,linux/386 -t ghcr.io/$ORG_NAME/$REPO_NAME:$IMAGE_ID -t ghcr.io/$ORG_NAME/$REPO_NAME:latest --push . -f Dockerfile
