name: Guardrails

on:
  workflow_call:
    inputs:
      conftest_version:
        type: string
        required: false
        default: "0.39.2"
        description: 'conftest version'        
   
jobs:
  guardrails:
    runs-on: ["self-hosted","Linux","ARM64","runner-devops"]
    steps:
    - name: Setup terraform
      uses: doliveiraorg/custom-workflows/.github/actions/conftest@main
