name: Guardrails

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  guardrails:
    runs-on: ["self-hosted","Linux","ARM64","runner-devops"]
    outputs:
      msg: ${{ steps.check-conftest.outputs.msg }}    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         fetch-depth: 0    
    - name: Checkout conftest repo
      uses: doliveiraorg/custom-workflows/.github/actions/conftest@main
      with:
        bot_github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
    - name: Get changed files#
      id: changed-files
      uses: tj-actions/changed-files@v36
    - name: Check conftest
      id: check-conftest
      run: |
          TEMP_FILE=$(mktemp)
          CONFTEST_POLICIES_PATH="policies/kubernetes/argocd"
          CONFTEST_NAMESPACE="argocd"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}
          do
              conftest test $file --policy $CONFTEST_POLICIES_PATH --no-fail -n argocd -o json | jq -r '.[] | ((.warnings[]?.msg // []), (.failures[]?.msg // []) | select(. != null))' | tr -d '[]"' | sed '/^\s*$/d' | tee -a $TEMP_FILE
          done
          echo "msg=$(cat $TEMP_FILE | base64 | tr -d '\n')" >> $GITHUB_OUTPUT 
          
  open-pr:
    runs-on: ["self-hosted","Linux","ARM64","runner-devops"]
    needs: guardrails
    steps:          
    - name: Check conftest
      run: |
            echo ${{ needs.guardrails.outputs.msg }} | base64 --decode
#    - name: Check conftest
#      run: |
#          for file in ${{ steps.changed-files.outputs.all_changed_files }}
#          do
#              conftest test $file --policy $CONFTEST_POLICIES_PATH --no-fail -n argocd -o json | jq -r '.[] | ((.warnings[]?.msg // []), (.failures[]?.msg // []) | select(. != null))' | tr -d '[]"' | sed '/^\s*$/d' | tee $TEMP_FILE
#              CONFTEST_POLICIES_PATH="policies/kubernetes/argocd"
#              CONFTEST_NAMESPACE="argocd"
#              CONFTEST_FAILURES="$(conftest test $file --policy $CONFTEST_POLICIES_PATH --no-fail -n $CONFTEST_NAMESPACE -o json | jq -r '.[0].failures')"
#              CONFTEST_WARNINGS="$(conftest test $file --policy $CONFTEST_POLICIES_PATH --no-fail -n $CONFTEST_NAMESPACE -o json | jq -r '.[0].warnings')"
#              CONFTEST_SUCCESS="$(conftest test $file --policy $CONFTEST_POLICIES_PATH --no-fail -n $CONFTEST_NAMESPACE -o json | jq -r '.[0].success')"
#              if [[ $CONFTEST_FAILURES != "null" ]]
#              then
#                  echo "start"
#                  echo $CONFTEST_FAILURES
#                  echo "end"
#              fi
#          done          
#           conftest test $file --policy $CONFTEST_POLICIES_PATH --no-fail -n argocd -o json
#    - name: Update Pull Request with Results
#      id: update-pr
#      if: steps.conftest-scan.outputs.logs != '' && steps.file_check.outputs.helmfile == 'true'
#      uses: actions/github-script@v6
#      env:
#        CT_RESULT_BASE64: ${{ steps.conftest-scan.outputs.logs }}
#        RUN_ID: ${{ github.run_id }}
#      with:
#        github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
#        result-encoding: string
#        script: |
#            github.rest.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: "this is my body"
#            })
#      continue-on-error: true
