name: Guardrails

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  guardrails:
    runs-on: ["self-hosted","Linux","ARM64","runner-devops"]
    steps:
    - name: Setup terraform
      uses: doliveiraorg/custom-workflows/.github/actions/conftest@main
      with:
        bot_github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
    - name: debug
      run: |
             ls -la policies/
