name: Guardrails

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  guardrails:
    runs-on: ["self-hosted","Linux","ARM64","runner-devops"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         ref: '${{ github.head_ref }}'
         path: argocd
         fetch-depth: 0    
    - name: Setup terraform
      uses: doliveiraorg/custom-workflows/.github/actions/conftest@main
      with:
        bot_github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
    - name: debug
      run: |
             ls -la

#            ARGOCD_TEMPLATES=("app.yaml" "app.yml" "project.yaml" "project.yml")
#            ARGOCD_FILES=$(git diff --name-only HEAD^1 HEAD)
#            for file_path in $ARGOCD_FILES; do
#              if [ -e $file_path ];
#              then
#                OIFS="$IFS"
#                IFS='/'
#                read -a FILE_AS_LIST <<< "$file_path"
#                IFS="$OIFS"
#                FILE="${FILE_AS_LIST[${#FILE_AS_LIST[@]}-1]}"
#                if echo "${ARGOCD_TEMPLATES[@]}" | grep -wq "$FILE";
#                then
#                    cat $file_path
#                fi
#              fi
#            done
