
name: CD

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment para deploy'
        required: true
      repository:
        type: string
        description: 'Repositorio da imagem'
        required: true   
      tag:
        type: string
        description: 'Tag da imagem'
        required: true 
jobs:
  diff:
    runs-on: self-hosted
    name: Helfile diff
    steps:
    - uses: actions/checkout@v2
    - name: Helmfile diff
      run: |
             helmfile -e ${{ inputs.environment }} diff --set image.repository=${{ inputs.repository }},image.tag=${{ inputs.tag }}

  deploy:
    runs-on: self-hosted
    name: Helmfile deploy
    needs: [diff] 
    steps:
    - uses: actions/checkout@v2
    - name: Helmfile deploy
      run: |
            helmfile -e ${{ inputs.environment }} --set image.repository=${{ inputs.repository }},image.tag=${{ inputs.tag }} apply
