
name: CD

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment para deploy'
        required: true
      repository:
        type: string
        description: 'Repositorio da imagem'
        required: true   
      tag:
        type: string
        description: 'Tag da imagem'
        required: true 
jobs:
  diff:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Helmfile diff
      run: |
            echo ${{ inputs.repository }}
            echo ${{ inputs.tag }}
#             helmfile -e ${{ inputs.environment }} diff --set image.repository=teste,image.tag=teste

             
  deploy:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [diff] 
    steps:
    - uses: actions/checkout@v2
    - name: Helmfile deploy
      run: |
              echo ${{ inputs.repository }}
              echo ${{ inputs.tag }}
#             helmfile -e prod sync
