
name: CD

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment para deploy'
        required: false
      repository:
        type: string
        description: 'Repositorio da imagem'
        required: false      
      tag:
        type: string
        description: 'Tag da imagem'
        required: false      
jobs:
  diff:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
            echo ${{ inputs.repository }}
            echo ${{ inputs.tag }}
#             helmfile -e ${{ inputs.environment }} diff --set image.repository=teste,image.tag=teste

             
#  deploy:
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@v2
#    - name: Run a one-line script
#      run: |
#             helmfile -e prod sync
