
name: CD

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment para deploy'
        required: true
      repository:
        type: string
        description: 'Repositorio da imagem'
        required: true   
      tag:
        type: string
        description: 'Tag da imagem'
        required: true 
      helm_version:
        type: string
        description: 'versao do helm'
        required: false
        default: '3.7.0'
      helmfile_path:
        type: string
        description: 'Caminho para o helmfile'
        required: false
        default: '.' 
      deploy_approvers:
        type: string
        description: 'aprovadores'
        required: false
        default: 'org_approvers'
      deploy_min_approvers:
        type: number
        description: 'qtd de aprovadores'
        required: false
        default: 1
        
jobs:
  diff:
    runs-on: [ doliveiraorg-k8s-runner ]
    name: diff ${{ inputs.environment }}
    steps:
    - name: helmfile setup
      uses: doliveiraorg/custom-workflows/.github/actions/helmfile@main
    - name: helmfile diff
      run: |
             helmfile --environment ${{ inputs.environment }} --file ${{ inputs.helmfile_path }}/helmfile.yaml diff --set image.repository=${{ inputs.repository }},image.tag=${{ inputs.tag }}  
  approve:
    runs-on: ubuntu-latest
    name: approve ${{ inputs.environment }}
    needs: [diff]
    steps:
    - name: Manual Workflow Approval
      uses: trstringer/manual-approval@v1.6.0
      with:
       approvers: diego1277
       secret: ${{ secrets.GITHUB_TOKEN }}
       minimum-approvals: ${{ inputs.deploy_min_approvers }}
   
  deploy:
    runs-on: [ doliveiraorg-k8s-runner ]
    name: deploy ${{ inputs.environment }}
    needs: [approve]
    steps:
    - name: helmfile setup
      uses: doliveiraorg/custom-workflows/.github/actions/helmfile@main    
    - name: helmfile deploy ${{ inputs.environment }}
      run: |
             helmfile --environment ${{ inputs.environment }} --file ${{ inputs.helmfile_path }}/helmfile.yaml apply --set image.repository=${{ inputs.repository }},image.tag=${{ inputs.tag }} 
