
name: CD

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment para deploy'
        required: true
      repository:
        type: string
        description: 'Repositorio da imagem'
        required: true   
      tag:
        type: string
        description: 'Tag da imagem'
        required: true 
      helmfile_path:
        type: string
        description: 'Caminho para o helmfile'
        required: false
        default: '.'     
jobs:
  diff:
    runs-on: self-hosted
    name: helmfile diff ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v2
    - name: Helmfile diff
      run: |
             helmfile --environment ${{ inputs.environment }} --file ${{ inputs.helmfile_path }}/helmfile.yaml diff --set image.repository=${{ inputs.repository }},image.tag=${{ inputs.tag }}

  deploy:
    runs-on: self-hosted
    name: helmfile deploy ${{ inputs.environment }}
    needs: [diff] 
    steps:
    - uses: actions/checkout@v2
    - name: Helmfile deploy
      run: |
             helmfile --environment ${{ inputs.environment }} --file ${{ inputs.helmfile_path }}/helmfile.yaml apply --set image.repository=${{ inputs.repository }},image.tag=${{ inputs.tag }} 
