name: Cleanup

on:
  workflow_call:
    inputs:    
      organization:
        type: string
        description: 'Nome da ga organization'
        required: false
        default: ${{ github.repository_owner }}
      repository:
        type: string
        description: 'Repositorio'
        required: false
        default: ${{ github.repository }}
      package_name:
        type: string
        description: 'Nome do package'
        required: false
        
jobs:
  plan:
    runs-on: ["self-hosted","Linux","ARM64","runner-devops"]
    name: cleanup
    steps:
    - name: repo name env
      env: 
        PACKAGE_NAME_TEMP: ${{ inputs.package_name }}
      run: |
        if [ -z "$PACKAGE_NAME_TEMP" ]; then
            PACKAGE_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
            echo $PACKAGE_NAME
        else
            echo $PACKAGE_NAME_TEMP
        fi    
#    - uses: smartsquaregmbh/delete-old-packages@v0.7.0
#      with:
#        token: ${{ secrets.GH_ACCESS_TOKEN }}
#        organization: ${{ inputs.organization }}
#        type: 'container'
#        keep: 3    
#        names: |
#           ${{ github.repository }}   
