name: Cleanup

on:
  workflow_call:
    inputs:    
      organization:
        type: string
        description: 'Nome da ga organization'
        required: false
        default: ${{ github.repository_owner }}
      repository:
        type: string
        description: 'Repositorio'
        required: false
        default: ${{ github.repository }}
jobs:
  plan:
    runs-on: ["self-hosted","Linux","ARM64","runner-devops"]
    name: cleanup
    steps:
    - name: repo name env
      run: |
        PACKAGE_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f3)
        echo $PACKAGE_NAME
#    - uses: smartsquaregmbh/delete-old-packages@v0.7.0
#      with:
#        token: ${{ secrets.GH_ACCESS_TOKEN }}
#        organization: ${{ inputs.organization }}
#        type: 'container'
#        keep: 3    
#        names: |
#           ${{ github.repository }}   
