
name: CD

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment para deploy'
        required: true
      repository:
        type: string
        description: 'Repositorio da imagem'
        required: true   
      tag:
        type: string
        description: 'Tag da imagem'
        required: true 
      helm_version:
        type: string
        description: 'versao do helm'
        required: false
        default: '3.7.0'
      helmfile_path:
        type: string
        description: 'Caminho para o helmfile'
        required: false
        default: '.' 
      deploy_approvers:
        type: string
        description: 'aprovadores'
        required: false
        default: 'org_approvers'
      deploy_min_approvers:
        type: number
        description: 'qtd de aprovadores'
        required: false
        default: 1
        
jobs:
  diff:
    runs-on: [ doliveiraorg-k8s-runner ]
    name: diff ${{ inputs.environment }}
    outputs:
      helmfile_deploy: ${{ steps.helmfile_diff.outputs.helmfile_deploy }}
    steps:
    - name: helmfile setup
      uses: doliveiraorg/custom-workflows/.github/actions/helmfile@main
    - name: helmfile diff
      id: helmfile_diff
      run: |
             helmfile --environment ${{ inputs.environment }} --file ${{ inputs.helmfile_path }}/helmfile.yaml diff --set image.repository=${{ inputs.repository }},image.tag=${{ inputs.tag }} --detailed-exitcode 2>&1 | tee diff.log 
              
             HELMFILE_DEPLOY="true"

             if grep -qwE 'No affected releases' diff.log;then
                HELMFILE_DEPLOY="false"
             fi

             echo "helmfile_deploy=$HELMFILE_DEPLOY" > $GITHUB_OUTPUT


    - uses: gr2m/create-or-update-pull-request-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: "feature"
        author: "Lorem J. Ipsum <lorem@example.com>"
        path: "data/"
        commit-message: "feat: data updated"
