name: Packer

on:
  workflow_call:
    inputs:
      dispatches_repo:
        type: string
        description: 'terraform repo'
        default: 'https://api.github.com/repos/doliveiraorg/terraform/dispatches'
        required: false
      dispatches_event_type:
        type: string
        description: 'dispatches event type'
        required: true           
      packer_directory:
        type: string
        description: 'packer directory'
        required: true
      packer_version:
        type: string
        description: 'packer version'
        default: '1.8.5'
        required: false
      packer_var_file:
        type: string
        description: 'packer var file'
        required: true  
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        terraform_path: ${{ env.TERRAFORM_PATH }}
        aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
    - name: Setup HashiCorp Packer
      uses: hashicorp/setup-packer@v2.0.0
      with:
        version: "${{ inputs.packer_version }}" 
    - name: Set VERSION
      run: |
             echo "VERSION=$(date +%Y%m%d).${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
      
    - name: Packer init
      run: |
            packer init -var-file=${{ inputs.packer_var_file }} -var "version=${VERSION}" ${{ inputs.packer_directory }} 
    - name: Packer validate
      run: |
            packer validate -var-file=${{ inputs.packer_var_file }} -var "version=${VERSION}" ${{ inputs.packer_directory }}
    - name: Packer build
      run: |
            packer build -var-file=${{ inputs.packer_var_file }} -var "version=${VERSION}" ${{ inputs.packer_directory }}            
    - name: Trigger terraform workflow
      run: |
            curl --fail \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.TERRAFORM_REPO_TOKEN }}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              ${{ inputs.dispatches_repo }} \
              -d '{"event_type":"${{ inputs.dispatches_event_type }}","client_payload":{"unit":false,"integration":true}}'
          
#https://developer.hashicorp.com/packer/docs/commands/init
#curl -i https://api.github.com/users/octocat     
