name: Packer

on:
  workflow_call:
    inputs:
      dispatches_repo:
        type: string
        description: 'terraform repo'
        default: 'https://api.github.com/repos/doliveiraorg/testes-github-actions/dispatches'
        required: false
      dispatches_event_type:
        type: string
        description: 'dispatches event type'
        required: true           
      packer_directory:
        type: string
        description: 'packer directory'
        required: true
      packer_version:
        type: string
        description: 'packer version'
        default: '1.8.5'
        required: false
      ansible_directory:
        type: string
        description: 'ansible directory'
        default: 'packer/'
        required: false       
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        aws-region: "${{ secrets.AWS_REGION }}"
    - name: Setup HashiCorp Packer
      uses: hashicorp/setup-packer@v2.0.0
      with:
        version: "${{ inputs.packer_version }}"      
    - name: Packer init
      run: |
            packer init .
      working-directory: "${{ inputs.packer_directory }}"
    - name: Packer validate
      run: |
            packer validate .
      working-directory: "${{ inputs.packer_directory }}"
    - name: Trigger terraform workflow
      run: |
            curl --fail \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.TERRAFORM_REPO_TOKEN }}xxx"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              ${{ inputs.dispatches_repo }} \
              -d '{"event_type":"${{ inputs.dispatches_event_type }}","client_payload":{"unit":false,"integration":true}}'
          
            echo $?
#            if [ $? != 0 ]
#            then
#                 echo "Error in githubactions dispatches trigger event"
#                 exit 1
#            fi
#https://developer.hashicorp.com/packer/docs/commands/init
#curl -i https://api.github.com/users/octocat     
