
name: Terraform

on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        description: 'versao do terraform'
        default: 1.3.3
        required: false
      aws_access_key_id:
        type: string
        required: false
        description: 'aws key id'
      aws_secret_access_key:
        type: string
        required: false
        description: 'aws secret'
      aws_region:
        type: string
        required: false
        description: 'aws region'        
        
jobs:
  plan:
    #runs-on: [ doliveiraorg-k8s-runner ]
    #name: diff ${{ inputs.environment }}
    runs-on: [ubuntu-latest]
    name: plan
    steps:
    - name: terraform setup
      uses: doliveiraorg/custom-workflows/.github/actions/terraform@main
      with:
        terraform_version: ${{ inputs.terraform_version }}       
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        aws-region: "${{ secrets.AWS_REGION }}"     
    - name: terraform plan
      id: plan
      run: |
             terraform version
