name: Terraform

on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        description: 'versao do terraform'
        default: 1.3.3
        required: false
      terragrunt_version:
        type: string
        required: false
        description: 'versao do terragrunt'
        default: '0.39.2'        
      terragrunt_path:
        type: string
        required: true
        description: 'path terragrunt'
      
        
jobs:
  plan:
    #runs-on: [ doliveiraorg-k8s-runner ]
    runs-on: [ubuntu-latest]
    name: plan
    steps:
    - name: terragrunt action
      uses: doliveiraorg/custom-workflows/.github/actions/terragrunt@main
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terragrunt_version: ${{ inputs.terragrunt_version }}
        terragrunt_path: ${{ inputs.terragrunt_path }}
        gh_token: ${{ secrets.GH_TOKEN }}
        gh_user: ${{ secrets.GH_USER }}
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_region: ${{ secrets.AWS_REGION }}
