
name: Terraform

on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        description: 'versao do terraform'
        default: 1.3.3
        required: false
      terragrunt_version:
        type: string
        required: false
        description: 'versao do terragrunt'
        default: '0.39.2'        
      aws_access_key_id:
        type: string
        required: false
        description: 'aws key id'
      aws_secret_access_key:
        type: string
        required: false
        description: 'aws secret'
      aws_region:
        type: string
        required: false
        description: 'aws region'
      terragrunt_path:
        type: string
        required: true
        description: 'path terragrunt'
        
jobs:
  plan:
    #runs-on: [ doliveiraorg-k8s-runner ]
    runs-on: [ubuntu-latest]
    name: plan
    steps:
    - uses: actions/checkout@v2
    - name: terraform setup
      uses: doliveiraorg/custom-workflows/.github/actions/terraform@main
      with:
        terraform_version: ${{ inputs.terraform_version }}       
        terragrunt_version: ${{ inputs.terragrunt_version }}               
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        aws-region: "${{ secrets.AWS_REGION }}"
    - name: setup git url.insteadof
      run: |
             git config --local --remove-section http."https://github.com/"
             git config --global url."https://${GH_USER}:${GH_TOKEN}@github.com/doliveiraorg".insteadOf "https://github.com/doliveiraorg"
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USER: ${{ secrets.GH_USER }}
    - name: terraform plan
      id: plan
      run: |
             terragrunt plan
      working-directory: ${{ inputs.terragrunt_path }}
