
name: Terraform

on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        description: 'Versao do terraform'
        default: 1.3.3
        required: false
        
jobs:
  plan:
    #runs-on: [ doliveiraorg-k8s-runner ]
    #name: diff ${{ inputs.environment }}
    runs-on: [ubuntu-latest]
    name: plan
    steps:
    - name: terraform setup
      uses: doliveiraorg/custom-workflows/.github/actions/terraform@main
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: plan
      id: plan
      run: |
             terraform version
