name: teste

on:
  workflow_call:
    inputs:
      myValues:
        type: string
        required: true
        description: 'deploy apenas realizado apenas em pull request'        

jobs:
  plan:
    runs-on: [ubuntu-latest]
    name: plan
    steps:
    - name: step1
      run: |
             echo ${{ inputs.myValues }}
