name: teste

on:
  pull_request_target:
    types:
      - opened
      - synchronize
  workflow_call:
  
jobs:
  plan:
    runs-on: [ubuntu-latest]
    name: plan
    steps:
    - name: step1
      run: |
             echo "step 1"
