name: teste

on:
  workflow_call:
    inputs:
      var_1: 
        type: string
        required: true
      var_2:
        type: string
        required: true
 
 jobs:
   job1:
     name: Primeiro job de teste
     runs-on: ubuntu-latest
     steps:
      - name: "primeiro step"
        run: echo "${{ inputs.var_1 }}"
      - name: "segundo step"
        runs: echo "${{ inputs.var_2 }}"
