name: teste

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
  
jobs:
  plan:
    name: teste
    steps:
    - uses: smartsquaregmbh/delete-old-packages@v0.7.0
      with:
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        organization: doliveiraorg
        type: 'container'
        keep: 3    
        names: |
          gobank    
